apiVersion: neutron.openstack.org/v1
kind: NeutronOvsAgent
metadata:
  name: neutron-ovsagent
spec:
  # Rabbit transport url
  rabbitTransportURL: rabbit://guest:eJNAlgHTTN8A6mclF6q6dBdL1@controller-0.internalapi.redhat.local:5672/?ssl=0
  # Debug
  debug: "True"
  openvswitchImage: docker.io/tripleotrain/rhel-binary-neutron-openvswitch-agent:current-tripleo
  label: compute
