// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/neutron-operator/pkg/apis/neutron/v1.NeutronOvsAgent":       schema_pkg_apis_neutron_v1_NeutronOvsAgent(ref),
		"github.com/neutron-operator/pkg/apis/neutron/v1.NeutronOvsAgentSpec":   schema_pkg_apis_neutron_v1_NeutronOvsAgentSpec(ref),
		"github.com/neutron-operator/pkg/apis/neutron/v1.NeutronOvsAgentStatus": schema_pkg_apis_neutron_v1_NeutronOvsAgentStatus(ref),
	}
}

func schema_pkg_apis_neutron_v1_NeutronOvsAgent(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NeutronOvsAgent is the Schema for the neutronovsagents API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/neutron-operator/pkg/apis/neutron/v1.NeutronOvsAgentSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/neutron-operator/pkg/apis/neutron/v1.NeutronOvsAgentStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/neutron-operator/pkg/apis/neutron/v1.NeutronOvsAgentSpec", "github.com/neutron-operator/pkg/apis/neutron/v1.NeutronOvsAgentStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_neutron_v1_NeutronOvsAgentSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NeutronOvsAgentSpec defines the desired state of NeutronOvsAgent",
				Properties: map[string]spec.Schema{
					"label": {
						SchemaProps: spec.SchemaProps{
							Description: "Label is the value of the 'daemon=' label to set on a node that should run the daemon",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"openvswitchImage": {
						SchemaProps: spec.SchemaProps{
							Description: "Image is the Docker image to run for the daemon",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"label", "openvswitchImage"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_neutron_v1_NeutronOvsAgentStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NeutronOvsAgentStatus defines the observed state of NeutronOvsAgent",
				Properties: map[string]spec.Schema{
					"count": {
						SchemaProps: spec.SchemaProps{
							Description: "Count is the number of nodes the daemon is deployed to",
							Type:        []string{"integer"},
							Format:      "int32",
						},
					},
				},
				Required: []string{"count"},
			},
		},
		Dependencies: []string{},
	}
}
