// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronOvsAgent) DeepCopyInto(out *NeutronOvsAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronOvsAgent.
func (in *NeutronOvsAgent) DeepCopy() *NeutronOvsAgent {
	if in == nil {
		return nil
	}
	out := new(NeutronOvsAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NeutronOvsAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronOvsAgentList) DeepCopyInto(out *NeutronOvsAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NeutronOvsAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronOvsAgentList.
func (in *NeutronOvsAgentList) DeepCopy() *NeutronOvsAgentList {
	if in == nil {
		return nil
	}
	out := new(NeutronOvsAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NeutronOvsAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronOvsAgentSpec) DeepCopyInto(out *NeutronOvsAgentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronOvsAgentSpec.
func (in *NeutronOvsAgentSpec) DeepCopy() *NeutronOvsAgentSpec {
	if in == nil {
		return nil
	}
	out := new(NeutronOvsAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronOvsAgentStatus) DeepCopyInto(out *NeutronOvsAgentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronOvsAgentStatus.
func (in *NeutronOvsAgentStatus) DeepCopy() *NeutronOvsAgentStatus {
	if in == nil {
		return nil
	}
	out := new(NeutronOvsAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronSriovAgent) DeepCopyInto(out *NeutronSriovAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronSriovAgent.
func (in *NeutronSriovAgent) DeepCopy() *NeutronSriovAgent {
	if in == nil {
		return nil
	}
	out := new(NeutronSriovAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NeutronSriovAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronSriovAgentList) DeepCopyInto(out *NeutronSriovAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NeutronSriovAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronSriovAgentList.
func (in *NeutronSriovAgentList) DeepCopy() *NeutronSriovAgentList {
	if in == nil {
		return nil
	}
	out := new(NeutronSriovAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NeutronSriovAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronSriovAgentSpec) DeepCopyInto(out *NeutronSriovAgentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronSriovAgentSpec.
func (in *NeutronSriovAgentSpec) DeepCopy() *NeutronSriovAgentSpec {
	if in == nil {
		return nil
	}
	out := new(NeutronSriovAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeutronSriovAgentStatus) DeepCopyInto(out *NeutronSriovAgentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeutronSriovAgentStatus.
func (in *NeutronSriovAgentStatus) DeepCopy() *NeutronSriovAgentStatus {
	if in == nil {
		return nil
	}
	out := new(NeutronSriovAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNController) DeepCopyInto(out *OVNController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNController.
func (in *OVNController) DeepCopy() *OVNController {
	if in == nil {
		return nil
	}
	out := new(OVNController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerList) DeepCopyInto(out *OVNControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVNController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerList.
func (in *OVNControllerList) DeepCopy() *OVNControllerList {
	if in == nil {
		return nil
	}
	out := new(OVNControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerSpec) DeepCopyInto(out *OVNControllerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerSpec.
func (in *OVNControllerSpec) DeepCopy() *OVNControllerSpec {
	if in == nil {
		return nil
	}
	out := new(OVNControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNControllerStatus) DeepCopyInto(out *OVNControllerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNControllerStatus.
func (in *OVNControllerStatus) DeepCopy() *OVNControllerStatus {
	if in == nil {
		return nil
	}
	out := new(OVNControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNMetadataAgent) DeepCopyInto(out *OVNMetadataAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNMetadataAgent.
func (in *OVNMetadataAgent) DeepCopy() *OVNMetadataAgent {
	if in == nil {
		return nil
	}
	out := new(OVNMetadataAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNMetadataAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNMetadataAgentList) DeepCopyInto(out *OVNMetadataAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVNMetadataAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNMetadataAgentList.
func (in *OVNMetadataAgentList) DeepCopy() *OVNMetadataAgentList {
	if in == nil {
		return nil
	}
	out := new(OVNMetadataAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVNMetadataAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNMetadataAgentSpec) DeepCopyInto(out *OVNMetadataAgentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNMetadataAgentSpec.
func (in *OVNMetadataAgentSpec) DeepCopy() *OVNMetadataAgentSpec {
	if in == nil {
		return nil
	}
	out := new(OVNMetadataAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVNMetadataAgentStatus) DeepCopyInto(out *OVNMetadataAgentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVNMetadataAgentStatus.
func (in *OVNMetadataAgentStatus) DeepCopy() *OVNMetadataAgentStatus {
	if in == nil {
		return nil
	}
	out := new(OVNMetadataAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVSNodeOsp) DeepCopyInto(out *OVSNodeOsp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVSNodeOsp.
func (in *OVSNodeOsp) DeepCopy() *OVSNodeOsp {
	if in == nil {
		return nil
	}
	out := new(OVSNodeOsp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVSNodeOsp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVSNodeOspList) DeepCopyInto(out *OVSNodeOspList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OVSNodeOsp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVSNodeOspList.
func (in *OVSNodeOspList) DeepCopy() *OVSNodeOspList {
	if in == nil {
		return nil
	}
	out := new(OVSNodeOspList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OVSNodeOspList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVSNodeOspSpec) DeepCopyInto(out *OVSNodeOspSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVSNodeOspSpec.
func (in *OVSNodeOspSpec) DeepCopy() *OVSNodeOspSpec {
	if in == nil {
		return nil
	}
	out := new(OVSNodeOspSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVSNodeOspStatus) DeepCopyInto(out *OVSNodeOspStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVSNodeOspStatus.
func (in *OVSNodeOspStatus) DeepCopy() *OVSNodeOspStatus {
	if in == nil {
		return nil
	}
	out := new(OVSNodeOspStatus)
	in.DeepCopyInto(out)
	return out
}
