/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group neutron --version v1beta1 --kind NeutronAPI --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// NeutronAPIDefaults -
type NeutronAPIDefaults struct {
	ContainerImageURL      string
	NeutronAPIRouteTimeout string
}

var neutronAPIDefaults NeutronAPIDefaults

// log is for logging in this package.
var neutronapilog = logf.Log.WithName("neutronapi-resource")

// SetupNeutronAPIDefaults - initialize NeutronAPI spec defaults for use with either internal or external webhooks
func SetupNeutronAPIDefaults(defaults NeutronAPIDefaults) {
	neutronAPIDefaults = defaults
	neutronapilog.Info("NeutronAPI defaults initialized", "defaults", defaults)
}

// SetupWebhookWithManager sets up the webhook with the Manager
func (r *NeutronAPI) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

//+kubebuilder:webhook:path=/mutate-neutron-openstack-org-v1beta1-neutronapi,mutating=true,failurePolicy=fail,sideEffects=None,groups=neutron.openstack.org,resources=neutronapis,verbs=create;update,versions=v1beta1,name=mneutronapi.kb.io,admissionReviewVersions=v1

var _ webhook.Defaulter = &NeutronAPI{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NeutronAPI) Default() {
	neutronapilog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this NeutronAPI spec
func (spec *NeutronAPISpec) Default() {
	// only container image validations go here
	if spec.ContainerImage == "" {
		spec.ContainerImage = neutronAPIDefaults.ContainerImageURL
	}
	spec.NeutronAPISpecCore.Default()
}

// Default - set defaults for this NeutronAPI spec core. This version gets used by OpenStackControlplane
func (spec *NeutronAPISpecCore) Default() {
	// nothing here yet
}

// TODO(user): change verbs to "verbs=create;update;delete" if you want to enable deletion validation.
//+kubebuilder:webhook:path=/validate-neutron-openstack-org-v1beta1-neutronapi,mutating=false,failurePolicy=fail,sideEffects=None,groups=neutron.openstack.org,resources=neutronapis,verbs=create;update,versions=v1beta1,name=vneutronapi.kb.io,admissionReviewVersions=v1

var _ webhook.Validator = &NeutronAPI{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NeutronAPI) ValidateCreate() (admission.Warnings, error) {
	neutronapilog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NeutronAPI) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	neutronapilog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NeutronAPI) ValidateDelete() (admission.Warnings, error) {
	neutronapilog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

func (spec *NeutronAPISpec) GetDefaultRouteAnnotations() (annotations map[string]string) {
	return spec.NeutronAPISpecCore.GetDefaultRouteAnnotations()
}

func (spec *NeutronAPISpecCore) GetDefaultRouteAnnotations() (annotations map[string]string) {
	annotations = map[string]string{
		"haproxy.router.openshift.io/timeout": neutronAPIDefaults.NeutronAPIRouteTimeout,
	}
	return
}
