/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group neutron --version v1beta1 --kind NeutronAPI --programmatic-validation --defaulting
//

package v1beta1

import (
	"fmt"

	rabbitmqv1 "github.com/openstack-k8s-operators/infra-operator/apis/rabbitmq/v1beta1"
	"github.com/openstack-k8s-operators/lib-common/modules/common/service"
	common_webhook "github.com/openstack-k8s-operators/lib-common/modules/common/webhook"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/validation/field"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// NeutronAPIDefaults -
type NeutronAPIDefaults struct {
	ContainerImageURL string
	APITimeout        int
}

var neutronAPIDefaults NeutronAPIDefaults

// log is for logging in this package.
var neutronapilog = logf.Log.WithName("neutronapi-resource")

// SetupNeutronAPIDefaults - initialize NeutronAPI spec defaults for use with either internal or external webhooks
func SetupNeutronAPIDefaults(defaults NeutronAPIDefaults) {
	neutronAPIDefaults = defaults
	neutronapilog.Info("NeutronAPI defaults initialized", "defaults", defaults)
}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *NeutronAPI) Default() {
	neutronapilog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this NeutronAPI spec
func (spec *NeutronAPISpec) Default() {
	// only container image validations go here
	if spec.ContainerImage == "" {
		spec.ContainerImage = neutronAPIDefaults.ContainerImageURL
	}
	spec.NeutronAPISpecCore.Default()
}

// Default - set defaults for this NeutronAPI spec core. This version gets used by OpenStackControlplane
func (spec *NeutronAPISpecCore) Default() {
	if spec.APITimeout == 0 {
		spec.APITimeout = neutronAPIDefaults.APITimeout
	}

	// Only migrate from deprecated field if the new field is not already set
	if spec.MessagingBus.Cluster == "" {
		rabbitmqv1.DefaultRabbitMqConfig(&spec.MessagingBus, spec.RabbitMqClusterName)
	}

	// Default NotificationsBus if NotificationsBusInstance is specified
	if spec.NotificationsBusInstance != nil && *spec.NotificationsBusInstance != "" {
		if spec.NotificationsBus == nil {
			// Initialize empty NotificationsBus - credentials will be created dynamically
			// to ensure separation from MessagingBus (RPC and notifications should never share credentials)
			spec.NotificationsBus = &rabbitmqv1.RabbitMqConfig{}
		}
		rabbitmqv1.DefaultRabbitMqConfig(spec.NotificationsBus, *spec.NotificationsBusInstance)
	}
}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *NeutronAPI) ValidateCreate() (admission.Warnings, error) {
	neutronapilog.Info("validate create", "name", r.Name)

	var allWarns []string
	allErrs := field.ErrorList{}
	basePath := field.NewPath("spec")

	warns, errs := r.Spec.ValidateCreate(basePath, r.Namespace)
	allWarns = append(allWarns, warns...)
	allErrs = append(allErrs, errs...)

	if len(allErrs) != 0 {
		return allWarns, apierrors.NewInvalid(GroupVersion.WithKind("NeutronAPI").GroupKind(), r.Name, allErrs)
	}

	return allWarns, nil
}

// ValidateCreate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate an NeutronAPI spec.
func (r *NeutronAPISpec) ValidateCreate(basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	return r.NeutronAPISpecCore.ValidateCreate(basePath, namespace)
}

func (r *NeutronAPISpecCore) ValidateCreate(basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(basePath.Child("override").Child("service"), r.Override.Service)...)

	allErrs = append(allErrs, ValidateDefaultConfigOverwrite(basePath, r.DefaultConfigOverwrite)...)

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, r.ValidateTopology(basePath, namespace)...)

	return allWarns, allErrs
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *NeutronAPI) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	neutronapilog.Info("validate update", "name", r.Name)

	oldNeutronAPI, ok := old.(*NeutronAPI)
	if !ok || oldNeutronAPI == nil {
		return nil, apierrors.NewInternalError(fmt.Errorf("unable to convert existing object"))
	}

	var allWarns []string
	allErrs := field.ErrorList{}
	basePath := field.NewPath("spec")

	warns, errs := r.Spec.ValidateUpdate(oldNeutronAPI.Spec, basePath, r.Namespace)
	allWarns = append(allWarns, warns...)
	allErrs = append(allErrs, errs...)

	if len(allErrs) != 0 {
		return allWarns, apierrors.NewInvalid(GroupVersion.WithKind("NeutronAPI").GroupKind(), r.Name, allErrs)
	}

	return allWarns, nil
}

// ValidateUpdate - Exported function wrapping non-exported validate functions,
// this function can be called externally to validate an neutron spec.
func (spec *NeutronAPISpec) ValidateUpdate(old NeutronAPISpec, basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	return spec.NeutronAPISpecCore.ValidateUpdate(old.NeutronAPISpecCore, basePath, namespace)
}

func (spec *NeutronAPISpecCore) ValidateUpdate(old NeutronAPISpecCore, basePath *field.Path, namespace string) ([]string, field.ErrorList) {
	var allErrs field.ErrorList
	var allWarns []string

	// Validate deprecated fields using reflection-based validation
	warns, errs := spec.validateDeprecatedFieldsUpdate(old, basePath)
	allWarns = append(allWarns, warns...)
	allErrs = append(allErrs, errs...)

	// validate the service override key is valid
	allErrs = append(allErrs, service.ValidateRoutedOverrides(basePath.Child("override").Child("service"), spec.Override.Service)...)
	// validate the defaultConfigOverwrite is valid
	allErrs = append(allErrs, ValidateDefaultConfigOverwrite(basePath, spec.DefaultConfigOverwrite)...)

	// When a TopologyRef CR is referenced, fail if a different Namespace is
	// referenced because is not supported
	allErrs = append(allErrs, spec.ValidateTopology(basePath, namespace)...)

	return allWarns, allErrs
}

// getDeprecatedFields returns the centralized list of deprecated fields for NeutronAPISpecCore
func (spec *NeutronAPISpecCore) getDeprecatedFields(old *NeutronAPISpecCore) []common_webhook.DeprecatedFieldUpdate {
	// Get new field value (handle nil NotificationsBus)
	var newNotifBusCluster *string
	if spec.NotificationsBus != nil {
		newNotifBusCluster = &spec.NotificationsBus.Cluster
	}

	deprecatedFields := []common_webhook.DeprecatedFieldUpdate{
		{
			DeprecatedFieldName: "rabbitMqClusterName",
			NewFieldPath:        []string{"messagingBus", "cluster"},
			NewDeprecatedValue:  &spec.RabbitMqClusterName,
			NewValue:            &spec.MessagingBus.Cluster,
		},
		{
			DeprecatedFieldName: "notificationsBusInstance",
			NewFieldPath:        []string{"notificationsBus", "cluster"},
			NewDeprecatedValue:  spec.NotificationsBusInstance,
			NewValue:            newNotifBusCluster,
		},
	}

	// If old spec is provided (UPDATE operation), add old values
	if old != nil {
		deprecatedFields[0].OldDeprecatedValue = &old.RabbitMqClusterName
		deprecatedFields[1].OldDeprecatedValue = old.NotificationsBusInstance
	}

	return deprecatedFields
}

// validateDeprecatedFieldsCreate validates deprecated fields during CREATE operations
func (spec *NeutronAPISpecCore) validateDeprecatedFieldsCreate(basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list (without old values for CREATE)
	deprecatedFieldsUpdate := spec.getDeprecatedFields(nil)

	// Convert to DeprecatedField list for CREATE validation
	deprecatedFields := make([]common_webhook.DeprecatedField, len(deprecatedFieldsUpdate))
	for i, df := range deprecatedFieldsUpdate {
		deprecatedFields[i] = common_webhook.DeprecatedField{
			DeprecatedFieldName: df.DeprecatedFieldName,
			NewFieldPath:        df.NewFieldPath,
			DeprecatedValue:     df.NewDeprecatedValue,
			NewValue:            df.NewValue,
		}
	}

	return common_webhook.ValidateDeprecatedFieldsCreate(deprecatedFields, basePath), nil
}

// validateDeprecatedFieldsUpdate validates deprecated fields during UPDATE operations
func (spec *NeutronAPISpecCore) validateDeprecatedFieldsUpdate(old NeutronAPISpecCore, basePath *field.Path) ([]string, field.ErrorList) {
	// Get deprecated fields list with old values
	deprecatedFields := spec.getDeprecatedFields(&old)
	return common_webhook.ValidateDeprecatedFieldsUpdate(deprecatedFields, basePath)
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *NeutronAPI) ValidateDelete() (admission.Warnings, error) {
	neutronapilog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}

func (spec *NeutronAPISpec) GetDefaultRouteAnnotations() (annotations map[string]string) {
	return spec.NeutronAPISpecCore.GetDefaultRouteAnnotations()
}

func (spec *NeutronAPISpecCore) GetDefaultRouteAnnotations() (annotations map[string]string) {
	return map[string]string{
		"haproxy.router.openshift.io/timeout": fmt.Sprintf("%ds", neutronAPIDefaults.APITimeout),
	}
}

func ValidateDefaultConfigOverwrite(
	basePath *field.Path,
	validateConfigOverwrite map[string]string,
) field.ErrorList {
	var errors field.ErrorList
	for requested := range validateConfigOverwrite {
		if requested != "policy.yaml" {
			errors = append(
				errors,
				field.Invalid(
					basePath.Child("defaultConfigOverwrite"),
					requested,
					"Only the following keys are valid: policy.yaml",
				),
			)
		}
	}
	return errors
}

// SetDefaultRouteAnnotations sets HAProxy timeout values of the route
func (spec *NeutronAPISpecCore) SetDefaultRouteAnnotations(annotations map[string]string) {
	const haProxyAnno = "haproxy.router.openshift.io/timeout"
	// Use a custom annotation to flag when the operator has set the default HAProxy timeout
	// With the annotation func determines when to overwrite existing HAProxy timeout with the APITimeout
	const neutronAnno = "api.neutron.openstack.org/timeout"
	valNeutronAPI, okNeutronAPI := annotations[neutronAnno]
	valHAProxy, okHAProxy := annotations[haProxyAnno]
	// Human operator set the HAProxy timeout manually
	if !okNeutronAPI && okHAProxy {
		return
	}
	// Human operator modified the HAProxy timeout manually without removing the NeutronAPI flag
	if okNeutronAPI && okHAProxy && valNeutronAPI != valHAProxy {
		delete(annotations, neutronAnno)
		return
	}
	timeout := fmt.Sprintf("%ds", spec.APITimeout)
	annotations[neutronAnno] = timeout
	annotations[haProxyAnno] = timeout
}
