---
- project:
    name: openstack-k8s-operators/neutron-operator
    github-check:
      jobs:
        - openstack-meta-content-provider:
            vars:
              cifmw_bop_openstack_release: master
              cifmw_bop_dlrn_baseurl: "https://trunk.rdoproject.org/centos9-master"
              cifmw_repo_setup_branch: master
        - neutron-operator-tempest-multinode
